{
 "title": "Distribuzione delle Ore e Stato Lavorativo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciclo",
    "label": "Ciclo",
    "query": "select distinct ciclo from core.students order by ciclo"
   },
   {
    "name": "anno",
    "label": "Anno",
    "query": "select distinct anno from core.students_courses order by anno"
   }
  ]
 },
 "panels": [
  { "title": "Stato Lavorativo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Studenti di Ciclo ${ciclo}",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT * FROM marts.stato_lavorativo where ciclo in (${ciclo:sqlstring})"
    }
   ]
  },
  { "title": "Distribuzione delle Ore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Distribuzione ore per tipo per studenti - Ciclo ${ciclo}",
   "type": "barchart",
   "gridPos": { "h": 22, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\n  matricola,\n  nome,\n  cognome,\n  ciclo,\n  anno::text,\n  hour_les,\n  hour_ex,\n  hour_lab,\n  hour_tut,\n  insegnamenti\nFROM marts.distribuzione_di_ore \nWHERE ciclo IN (${ciclo:sqlstring}) AND anno = ${anno}"
    }
   ]
  },
  {
   "title": "Tipo Les per studenti - Ciclo ${ciclo} e Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 12 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\n  matricola,\n  nome,\n  cognome,\n  ciclo,\n  anno::text,\n  hour_les\n  -- hour_ex,\n  -- hour_lab,\n  -- hour_tut,\n  -- insegnamenti\nFROM marts.distribuzione_di_ore \nWHERE ciclo IN (${ciclo:sqlstring}) AND anno = ${anno}\norder by hour_les desc"
    }
   ]
  },
  {
   "title": "Tipo Ex per studenti - Ciclo ${ciclo} e Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\n  matricola,\n  nome,\n  cognome,\n  ciclo,\n  anno::text,\n  -- hour_les\n  hour_ex\n  -- hour_lab,\n  -- hour_tut,\n  -- insegnamenti\nFROM marts.distribuzione_di_ore \nWHERE ciclo IN (${ciclo:sqlstring}) AND anno = ${anno}\norder by hour_ex desc"
    }
   ]
  },
  {
   "title": "Tipo Lab per studenti - Ciclo ${ciclo} e Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 23 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\n  matricola,\n  nome,\n  cognome,\n  ciclo,\n  anno::text,\n  -- hour_les\n  -- hour_ex\n  hour_lab\n  -- hour_tut,\n  -- insegnamenti\nFROM marts.distribuzione_di_ore \nWHERE ciclo IN (${ciclo:sqlstring}) AND anno = ${anno}\norder by hour_lab desc"
    }
   ]
  },
  {
   "title": "Tipo Lab per studenti - Ciclo ${ciclo} e Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\n  matricola,\n  nome,\n  cognome,\n  ciclo,\n  anno::text,\n  -- hour_les\n  -- hour_ex\n  -- hour_lab,\n  hour_tut\n  -- insegnamenti\nFROM marts.distribuzione_di_ore \nWHERE ciclo IN (${ciclo:sqlstring}) AND anno = ${anno}\norder by hour_tut desc"
    }
   ]
  }
 ]
}