{
 "title": "Formazione e Pubblicazione",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciclo",
    "label": "Ciclo",
    "query": "select distinct ciclo from core.students order by ciclo"
   },
   {
    "name": "anno",
    "label": "Anno",
    "query": "select distinct extract(year from data_esame) as date from core.attivita_interne order by date"
   }
  ]
 },
 "panels": [
  { "title": "Ore di Formazione", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ore di Formazione per Ciclo ${ciclo}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select matricola, cognome, nome, ciclo, sum(ore_hard) as ore_hard, sum(ore_soft) as ore_soft, string_agg(corsi_ore, E'\\n\\n')\nfrom marts.ore_di_formazione \nwhere ciclo::int = ${ciclo}\nGROUP BY matricola, cognome, nome, ciclo\norder by (sum(ore_hard) + sum(ore_soft)) desc"
    }
   ]
  },
  {
   "title": "Ore di Formazione per Ciclo ${ciclo} e Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select matricola, cognome, nome, ciclo, anno::text, ore_hard, ore_soft, corsi_ore\nfrom marts.ore_di_formazione \nwhere anno::int = ${anno} and ciclo::int = ${ciclo}\n"
    }
   ]
  },
  {
   "title": "Ore di Formazione per Anno ${anno}",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select matricola, cognome, nome, anno::text, sum(ore_hard) as ore_hard, sum(ore_soft) as ore_soft, string_agg(corsi_ore, E'\\n\\n')\nfrom marts.ore_di_formazione \nwhere anno::int = ${anno}\nGROUP BY matricola, cognome, nome, anno\norder by (sum(ore_hard) + sum(ore_soft)) desc"
    }
   ]
  },
  { "title": "Pubblicazione per Studenti", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pubblicazioni per Anno ${anno}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select matricola, cognome, nome, anno::text, sum(publication_count) as \"Publication Count\", STRING_AGG(titles, '; ') as \"Titles\"\nFROM marts.pubblicazione \nwhere anno = ${anno}\ngroup by matricola, cognome, nome, anno\norder by sum(publication_count) desc"
    }
   ]
  },
  {
   "title": "Pubblicazioni per Ciclo ${ciclo}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select matricola, cognome, nome, ciclo::text, sum(publication_count) as \"Publication Count\", STRING_AGG(titles, '; ') as \"Titles\"\nFROM marts.pubblicazione \nwhere ciclo::int = ${ciclo}\ngroup by matricola, cognome, nome, ciclo\norder by sum(publication_count) desc"
    }
   ]
  },
  {
   "title": "Distribuzioni di Pubblicazioni per Ciclo ${ciclo}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select * from marts.pubblicazione_dettaglio\nwhere ciclo::integer = ${ciclo}"
    }
   ]
  },
  {
   "title": "Pubblicazioni per Ciclo ${ciclo} e per Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select * from marts.pubblicazione \nwhere ciclo::int = ${ciclo} and anno = ${anno}"
    }
   ]
  },
  { "title": "Pubblicazioni per Tutori", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Pubblicazioni per Anno ${anno}",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "select * from marts.pubblicazione_tutori \nwhere anno::int = ${anno}"
    }
   ]
  }
 ]
}