{
 "title": "Mobilita Internazionale",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciclo",
    "query": "select distinct ciclo from core.mobilita_internazionale_con_studenti order by ciclo"
   },
   {
    "name": "anno",
    "query": "select distinct anno from core.mobilita_internazionale_con_studenti order by anno"
   },
   { "name": "giorni_minimi", "query": "0,30,90,60,120,150,180" }
  ]
 },
 "panels": [
  {
   "title": "Mobilita per Studenti per Ciclo ${ciclo} e Anno ${anno}",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT *--matricola, cognome, nome, durata_giorni,  ciclo, anno, paese,  tipo  \nFROM marts.mobilita_internazionale \nwhere ciclo in (${ciclo:sqlstring}) and anno in (${anno:sqlstring})\n"
    }
   ]
  },
  {
   "title": "Numero di studenti (anni ${anno}) con almeno 120 giorni",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT count(*) \nFROM marts.mobilita_internazionale \nwhere anno in (${anno:sqlstring}) and durata_giorni > ${giorni_minimi}"
    }
   ]
  },
  {
   "title": "Durata Media per Paese per Ciclo ${ciclo} con Almeno ${giorni_minimi} Giorni",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT paese, avg(durata_giorni) as durata_giorni, count(*)::text as studenti, \n  string_agg(concat(cognome, ' ', nome, ' con ', durata_giorni, ' giorni', ' in ', ente), ' | ') as dettaglio\nFROM marts.mobilita_internazionale \nwhere ciclo in (${ciclo:sqlstring}) and durata_giorni> ${giorni_minimi}-- and anno in (${anno:sqlstring})\nGROUP BY paese\norder by avg(durata_giorni) desc\n"
    }
   ]
  },
  {
   "title": "Durata Media per Paese per Anno ${anno} con Almeno ${giorni_minimi} Giorni",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT paese,  avg(durata_giorni) as durata_giorni, count(*)::text as studenti, \nstring_agg(concat(cognome, ' ', nome, ' con ', durata_giorni, ' giorni', ' in ', ente), ' | ') as dettaglio\nFROM marts.mobilita_internazionale \nwhere anno in (${anno:sqlstring}) and durata_giorni> ${giorni_minimi}-- and \nGROUP BY paese\norder by avg(durata_giorni) desc"
    }
   ]
  }
 ]
}